---
manifest:
  defaults:
    remote: urob

  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
    # include corne with dongle pro_micro and xiao compatible
    - name: redmasters
      url-base: https://github.com/redmasters
    
  projects:
    - name: zmk-helpers
      revision: main
      path: modules/helpers
    - name: zmk-auto-layer
      revision: main
      path: modules/auto-layer
    - name: zmk-tri-state
      revision: main
      path: modules/tri-state
    # include corne with dongle pro_micro and xiao compatible
    - name: zmk-config-dongle
      remote: redmasters
      revision: feature/main-config
    # include dongle-display
    # - name: zmk-dongle-display
    #   remote: redmasters
    #   revision: main
    # ZMK with Zephyr namespaced under /zmk. This requires that ZMK imports
    # Zephyr with a path other than `zephyr` (as in `going-modular`).
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml

  self:
    path: config
