---
manifest:
  defaults:
    remote: urob

  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob

  projects:

    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml

    - name: zmk-auto-layer
      remote: urob
      revision: main

    - name: zmk-helpers
      revision: main
      path: modules/helpers

    - name: zmk-tri-state
      revision: main
      path: modules/tri-state

    - name: zmk
      revision: going-modular
      path: .
      import:
        file: app/west.yml
        path-prefix: zmk

  self:
    path: config
